version: '3.8'

services:
  db:
    image: postgres:18-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    networks:
      - kittygram_network
  backend:
    image: ${DOCKER_USERNAME}/kittygram_backend:latest
    container_name: backend
    restart: always
    volumes:
      - static:/app/collected_static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - kittygram_network

  frontend:
    image: ${DOCKER_USERNAME}/kittygram_frontend:latest
    container_name: frontend
    volumes:
      - static:/app/build/static
    restart: always
    depends_on:
      - backend
    networks:
      - kittygram_network

  gateway:
    image: ${DOCKER_USERNAME}/kittygram_gateway:latest
    container_name: gateway
    ports:
      - "80:80"
    restart: always
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - backend
      - frontend
    networks:
      - kittygram_network

volumes:
  static:
  media:
  pg_data:


networks:
  kittygram_network:
    driver: bridge
